<a href="https://colab.research.google.com/github/peperjet/bc-ml/blob/main/dacon/dacon_260331.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
# 필수 import

# 1. 데이터 분석 기초 (판다스, 넘파이)
import pandas as pd
import numpy as np

# 2. 시각화 (데이터 분포 확인용 - 블로그 올릴 때 예뻐요!)
import matplotlib.pyplot as plt
import seaborn as sns

# 3. 머신러닝 모델 (가장 무난하고 강력한 랜덤포레스트 추천)
from sklearn.ensemble import RandomForestClassifier

# 4. 데이터 전처리 (글자를 숫자로 바꾸거나 데이터 나누기)
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

# 5. 성능 평가 (내 모델이 얼마나 잘 맞히나 확인)
from sklearn.metrics import accuracy_score

In [35]:
# 데이터 읽어오기
train = pd.read_csv('/content/train.csv')
test = pd.read_csv('/content/test.csv')
submission = pd.read_csv('/content/sample_submission.csv')

# 잘 불러와졌는지 상단 5줄만 확인!
train.head()

,id,type,fiberID,psfMag_u,psfMag_g,psfMag_r,psfMag_i,psfMag_z,fiberMag_u,fiberMag_g,...,petroMag_u,petroMag_g,petroMag_r,petroMag_i,petroMag_z,modelMag_u,modelMag_g,modelMag_r,modelMag_i,modelMag_z
0,0,QSO,601,23.198224,21.431953,21.314148,21.176553,21.171444,22.581309,21.644453,...,22.504317,21.431636,21.478312,21.145409,20.422446,22.749241,21.465534,21.364187,21.020605,21.147340
1,1,QSO,788,21.431355,20.708104,20.678850,20.703420,20.473229,21.868797,21.029773,...,21.360701,20.778968,20.889705,20.639812,20.646660,21.492955,20.758527,20.753925,20.693389,20.512314
2,2,QSO,427,17.851451,16.727898,16.679677,16.694640,16.641788,18.171890,17.033098,...,17.867253,16.738784,16.688874,16.744210,16.808006,17.818063,16.697434,16.641249,16.660177,16.688928
3,3,QSO,864,20.789900,20.040371,19.926909,19.843840,19.463270,21.039030,20.317165,...,20.433907,19.993727,19.985531,19.750917,19.455117,20.770711,20.001699,19.889798,19.758113,19.552855
4,4,STAR_RED_DWARF,612,26.454969,23.058767,21.471406,19.504961,18.389096,25.700632,23.629122,...,25.859229,22.426929,21.673551,19.610012,18.376141,24.877052,23.147993,21.475342,19.487330,18.375655

In [36]:
# 정답 숫자로 변환
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
train['type'] = le.fit_transform(train['type'])

In [37]:
# x,y 분리

y = train['type']
X = train.drop(['id', 'type'], axis=1)
X_test = test

In [38]:
#데이터 보양 보기

train.head()
test.head()
train.shape, test.shape

((199991, 23), (10009, 22))

In [39]:
# 컬럼 이름 보기
print(train.columns)
print(test.columns)

Index(['id', 'type', 'fiberID', 'psfMag_u', 'psfMag_g', 'psfMag_r', 'psfMag_i',
       'psfMag_z', 'fiberMag_u', 'fiberMag_g', 'fiberMag_r', 'fiberMag_i',
       'fiberMag_z', 'petroMag_u', 'petroMag_g', 'petroMag_r', 'petroMag_i',
       'petroMag_z', 'modelMag_u', 'modelMag_g', 'modelMag_r', 'modelMag_i',
       'modelMag_z'],
      dtype='object')
Index(['id', 'fiberID', 'psfMag_u', 'psfMag_g', 'psfMag_r', 'psfMag_i',
       'psfMag_z', 'fiberMag_u', 'fiberMag_g', 'fiberMag_r', 'fiberMag_i',
       'fiberMag_z', 'petroMag_u', 'petroMag_g', 'petroMag_r', 'petroMag_i',
       'petroMag_z', 'modelMag_u', 'modelMag_g', 'modelMag_r', 'modelMag_i',
       'modelMag_z'],
      dtype='object')

In [40]:
# 데이터 타입 보기
train.info()
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 199991 entries, 0 to 199990
Data columns (total 23 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   id          199991 non-null  int64
 1   type        199991 non-null  int64
 2   fiberID     199991 non-null  int64
 3   psfMag_u    199991 non-null  float64
 4   psfMag_g    199991 non-null  float64
 5   psfMag_r    199991 non-null  float64
 6   psfMag_i    199991 non-null  float64
 7   psfMag_z    199991 non-null  float64
 8   fiberMag_u  199991 non-null  float64
 9   fiberMag_g  199991 non-null  float64
 10  fiberMag_r  199991 non-null  float64
 11  fiberMag_i  199991 non-null  float64
 12  fiberMag_z  199991 non-null  float64
 13  petroMag_u  199991 non-null  float64
 14  petroMag_g  199991 non-null  float64
 15  petroMag_r  199991 non-null  float64
 16  petroMag_i  199991 non-null  float64
 17  petroMag_z  199991 non-null  float64
 18  modelMag_u  199991 non-null  float64
 19  modelMag_g  199991 non-null  float64
 20  modelMag_r  199991 non-null  float64
 21  modelMag_i  199991 non-null  float64
 22  modelMag_z  199991 non-null  float64
dtypes: float64(20), int64(3)
memory usage: 35.1 MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10009 entries, 0 to 10008
Data columns (total 22 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          10009 non-null  int64
 1   fiberID     10009 non-null  int64
 2   psfMag_u    10009 non-null  float64
 3   psfMag_g    10009 non-null  float64
 4   psfMag_r    10009 non-null  float64
 5   psfMag_i    10009 non-null  float64
 6   psfMag_z    10009 non-null  float64
 7   fiberMag_u  10009 non-null  float64
 8   fiberMag_g  10009 non-null  float64
 9   fiberMag_r  10009 non-null  float64
 10  fiberMag_i  10009 non-null  float64
 11  fiberMag_z  10009 non-null  float64
 12  petroMag_u  10009 non-null  float64
 13  petroMag_g  10009 non-null  float64
 14  petroMag_r  10009 non-null  float64
 15  petroMag_i  10009 non-null  float64
 16  petroMag_z  10009 non-null  float64
 17  modelMag_u  10009 non-null  float64
 18  modelMag_g  10009 non-null  float64
 19  modelMag_r  10009 non-null  float64
 20  modelMag_i  10009 non-null  float64
 21  modelMag_z  10009 non-null  float64
dtypes: float64(20), int64(2)
memory usage: 1.7 MB

In [41]:
# 결측치 확인(빈칸 찾기)

train.isnull().sum()
test.isnull().sum()

id            0
fiberID       0
psfMag_u      0
psfMag_g      0
psfMag_r      0
psfMag_i      0
psfMag_z      0
fiberMag_u    0
fiberMag_g    0
fiberMag_r    0
fiberMag_i    0
fiberMag_z    0
petroMag_u    0
petroMag_g    0
petroMag_r    0
petroMag_i    0
petroMag_z    0
modelMag_u    0
modelMag_g    0
modelMag_r    0
modelMag_i    0
modelMag_z    0
dtype: int64

In [42]:
# 문자열 컬럼 확인
train.select_dtypes(include='object').columns
test.select_dtypes(include='object').columns

Index([], dtype='object')

In [43]:
# 기초 통계
train.describe()
test.describe()

,id,fiberID,psfMag_u,psfMag_g,psfMag_r,psfMag_i,psfMag_z,fiberMag_u,fiberMag_g,fiberMag_r,...,petroMag_u,petroMag_g,petroMag_r,petroMag_i,petroMag_z,modelMag_u,modelMag_g,modelMag_r,modelMag_i,modelMag_z
count,10009.000000,10009.000000,10009.000000,10009.000000,10009.000000,10009.000000,10009.000000,10009.000000,10009.000000,10009.000000,...,10009.000000,10009.000000,10009.000000,10009.000000,10009.000000,10009.000000,10009.000000,10009.000000,10009.000000,10009.000000
mean,204995.000000,359.327805,20.987400,19.878440,19.280218,18.873165,18.618385,21.184506,20.091376,19.497732,...,20.715429,19.462021,18.995001,18.616519,18.411996,20.739001,19.534844,18.935095,18.522308,18.281069
std,2889.493756,223.928862,2.111703,2.573890,1.709344,1.720713,1.702236,1.990940,1.865064,1.710070,...,2.807434,13.971203,1.979225,1.970463,2.373022,2.187025,1.957506,1.856617,1.796820,1.867582
min,199991.000000,1.000000,-7.248195,-42.663871,9.134712,-22.522266,13.349827,9.390439,8.188752,12.288183,...,-98.181975,-1348.068776,-23.908952,-8.356654,-64.917293,12.419765,13.617577,13.382832,12.955113,12.395695
25%,202493.000000,174.000000,19.655525,18.671025,18.037847,17.742016,17.424701,19.940430,18.892043,18.253627,...,19.249432,18.104265,17.475078,17.043615,16.805557,19.268471,18.064625,17.424393,16.971911,16.715685
50%,204995.000000,346.000000,20.854404,19.910333,19.444925,19.033283,18.594713,21.040735,20.071658,19.627904,...,20.371014,19.582955,19.197068,18.684269,18.171966,20.412702,19.541261,19.155839,18.635195,18.095883
75%,207497.000000,525.000000,22.160801,21.150040,20.489912,20.083814,19.878652,22.339213,21.402558,20.756306,...,21.803705,21.025719,20.428279,20.015701,19.815916,21.992969,20.981396,20.389215,19.970657,19.823902
max,209999.000000,1000.000000,37.681143,182.654452,31.883768,47.227391,34.946057,41.169991,47.160580,29.266687,...,65.392087,106.962571,41.850633,52.221528,74.747394,32.641240,28.814977,27.579664,26.471555,24.461973

In [44]:
# 분리

le = LabelEncoder()
train['type'] = le.fit_transform(train['type'])

y = train['type']
X = train.drop(['id', 'type'], axis=1)

X_test = test.copy()

In [45]:
# 숫자형 빈칸 채우기
num_cols = X.select_dtypes(include=['int64', 'float64']).columns
X[num_cols] = X[num_cols].fillna(X[num_cols].mean())
X_test[num_cols] = X_test[num_cols].fillna(X[num_cols].mean())

In [46]:
# 문자형 빈칸 채우기
cat_cols = X.select_dtypes(include=['object']).columns
for col in cat_cols:
    X[col] = X[col].fillna(X[col].mode()[0])
    X_test[col] = X_test[col].fillna(X[col].mode()[0])

In [47]:
# 문자열 입력 컬럼이 있으면 그때 변환
X = pd.get_dummies(X)
X_test = pd.get_dummies(X_test)

X, X_test = X.align(X_test, join='left', axis=1, fill_value=0)

In [48]:


# 정답 컬럼 숫자로 변환
le = LabelEncoder()
train['type'] = le.fit_transform(train['type'])

# 문제(X), 정답(y) 나누기
y = train['type']
X = train.drop(['id', 'type'], axis=1)

X_test = test.copy()

In [51]:
# 상단 데이터 보기
X.head()
X_test.head()

,id,fiberID,psfMag_u,psfMag_g,psfMag_r,psfMag_i,psfMag_z,fiberMag_u,fiberMag_g,fiberMag_r,...,petroMag_u,petroMag_g,petroMag_r,petroMag_i,petroMag_z,modelMag_u,modelMag_g,modelMag_r,modelMag_i,modelMag_z
0,199991,251,23.817399,22.508963,20.981106,18.517316,17.076079,25.053890,23.167848,21.335901,...,22.246697,22.796239,21.195315,18.584486,17.154284,25.391534,22.499435,21.011918,18.499341,17.091474
1,199992,386,22.806983,21.937111,20.335770,20.000512,19.527369,22.498565,22.186000,20.618879,...,21.729831,21.837511,20.196128,19.967204,19.683671,22.475338,21.853442,20.173169,19.796757,19.567372
2,199993,232,21.024250,19.235669,18.304061,17.808608,17.380113,21.205546,19.439533,18.344433,...,20.722629,18.710223,17.611851,17.158519,16.843986,20.579314,18.653338,17.562108,17.120529,16.708748
3,199994,557,20.503424,20.286261,20.197204,20.162419,20.059832,20.976132,20.611498,20.567262,...,20.329269,20.385262,20.129157,20.206574,20.212342,20.479879,20.280943,20.150499,20.206221,20.092909
4,199995,75,24.244851,22.668237,21.239333,19.284777,18.235939,25.681860,22.935289,21.642456,...,22.308298,22.957496,21.285033,19.299120,18.307526,25.489360,22.857290,21.191862,19.237964,18.280368

In [54]:
#크기확인

X.shape
X_test.shape

(10009, 22)

In [53]:
# 컬럼 확인

print(X.columns)
print(X_test.columns)

Index(['fiberID', 'psfMag_u', 'psfMag_g', 'psfMag_r', 'psfMag_i', 'psfMag_z',
       'fiberMag_u', 'fiberMag_g', 'fiberMag_r', 'fiberMag_i', 'fiberMag_z',
       'petroMag_u', 'petroMag_g', 'petroMag_r', 'petroMag_i', 'petroMag_z',
       'modelMag_u', 'modelMag_g', 'modelMag_r', 'modelMag_i', 'modelMag_z'],
      dtype='object')
Index(['id', 'fiberID', 'psfMag_u', 'psfMag_g', 'psfMag_r', 'psfMag_i',
       'psfMag_z', 'fiberMag_u', 'fiberMag_g', 'fiberMag_r', 'fiberMag_i',
       'fiberMag_z', 'petroMag_u', 'petroMag_g', 'petroMag_r', 'petroMag_i',
       'petroMag_z', 'modelMag_u', 'modelMag_g', 'modelMag_r', 'modelMag_i',
       'modelMag_z'],
      dtype='object')

In [55]:
# 타입 확인

X.info()
X_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 199991 entries, 0 to 199990
Data columns (total 21 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   fiberID     199991 non-null  int64
 1   psfMag_u    199991 non-null  float64
 2   psfMag_g    199991 non-null  float64
 3   psfMag_r    199991 non-null  float64
 4   psfMag_i    199991 non-null  float64
 5   psfMag_z    199991 non-null  float64
 6   fiberMag_u  199991 non-null  float64
 7   fiberMag_g  199991 non-null  float64
 8   fiberMag_r  199991 non-null  float64
 9   fiberMag_i  199991 non-null  float64
 10  fiberMag_z  199991 non-null  float64
 11  petroMag_u  199991 non-null  float64
 12  petroMag_g  199991 non-null  float64
 13  petroMag_r  199991 non-null  float64
 14  petroMag_i  199991 non-null  float64
 15  petroMag_z  199991 non-null  float64
 16  modelMag_u  199991 non-null  float64
 17  modelMag_g  199991 non-null  float64
 18  modelMag_r  199991 non-null  float64
 19  modelMag_i  199991 non-null  float64
 20  modelMag_z  199991 non-null  float64
dtypes: float64(20), int64(1)
memory usage: 32.0 MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10009 entries, 0 to 10008
Data columns (total 22 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          10009 non-null  int64
 1   fiberID     10009 non-null  int64
 2   psfMag_u    10009 non-null  float64
 3   psfMag_g    10009 non-null  float64
 4   psfMag_r    10009 non-null  float64
 5   psfMag_i    10009 non-null  float64
 6   psfMag_z    10009 non-null  float64
 7   fiberMag_u  10009 non-null  float64
 8   fiberMag_g  10009 non-null  float64
 9   fiberMag_r  10009 non-null  float64
 10  fiberMag_i  10009 non-null  float64
 11  fiberMag_z  10009 non-null  float64
 12  petroMag_u  10009 non-null  float64
 13  petroMag_g  10009 non-null  float64
 14  petroMag_r  10009 non-null  float64
 15  petroMag_i  10009 non-null  float64
 16  petroMag_z  10009 non-null  float64
 17  modelMag_u  10009 non-null  float64
 18  modelMag_g  10009 non-null  float64
 19  modelMag_r  10009 non-null  float64
 20  modelMag_i  10009 non-null  float64
 21  modelMag_z  10009 non-null  float64
dtypes: float64(20), int64(2)
memory usage: 1.7 MB

모델 만들기

In [56]:
model = RandomForestClassifier(
    n_estimators=50,
    max_depth=10,
    n_jobs=-1,
    random_state=42
)

In [57]:
# 학습

model.fit(X, y)

RandomForestClassifier(max_depth=10, n_estimators=50, n_jobs=-1,
                       random_state=42)

In [60]:
# 예측

X_test = test.copy()

if 'id' in X_test.columns:
    X_test = X_test.drop(['id'], axis=1)

In [61]:
print(X.columns)
print(X_test.columns)

Index(['fiberID', 'psfMag_u', 'psfMag_g', 'psfMag_r', 'psfMag_i', 'psfMag_z',
       'fiberMag_u', 'fiberMag_g', 'fiberMag_r', 'fiberMag_i', 'fiberMag_z',
       'petroMag_u', 'petroMag_g', 'petroMag_r', 'petroMag_i', 'petroMag_z',
       'modelMag_u', 'modelMag_g', 'modelMag_r', 'modelMag_i', 'modelMag_z'],
      dtype='object')
Index(['fiberID', 'psfMag_u', 'psfMag_g', 'psfMag_r', 'psfMag_i', 'psfMag_z',
       'fiberMag_u', 'fiberMag_g', 'fiberMag_r', 'fiberMag_i', 'fiberMag_z',
       'petroMag_u', 'petroMag_g', 'petroMag_r', 'petroMag_i', 'petroMag_z',
       'modelMag_u', 'modelMag_g', 'modelMag_r', 'modelMag_i', 'modelMag_z'],
      dtype='object')

In [62]:
# 가벼운 모델로 재시도

model = RandomForestClassifier(
    n_estimators=20,
    max_depth=5,
    n_jobs=-1,
    random_state=42
)

model.fit(X, y)
pred = model.predict(X_test)

submission['type'] = le.inverse_transform(pred)
submission.to_csv('submission.csv', index=False)