<a href="https://colab.research.google.com/github/peperjet/bc-ml/blob/main/real-estate-ml/apt2_260328.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# 데이터 불러오기
import pandas as pd

# train 이라는 객체에 'train.csv' 파일 할당해 줍니다
train = pd.read_csv('/content/train.csv')

In [2]:
# train 데이터 상위 5개행 출력
train.head()

,transaction_id,apartment_id,city,dong,jibun,apt,addr_kr,exclusive_use_area,year_of_completion,transaction_year_month,transaction_date,floor,transaction_real_price
0,0,7622,서울특별시,신교동,6-13,신현(101동),신교동 6-13 신현(101동),84.82,2002,200801,21~31,2.0,37500.0
1,1,5399,서울특별시,필운동,142,사직파크맨션,필운동 142 사직파크맨션,99.17,1973,200801,1~10,6.0,20000.0
2,2,3578,서울특별시,필운동,174-1,두레엘리시안,필운동 174-1 두레엘리시안,84.74,2007,200801,1~10,6.0,38500.0
3,3,10957,서울특별시,내수동,95,파크팰리스,내수동 95 파크팰리스,146.39,2003,200801,11~20,15.0,118000.0
4,4,10639,서울특별시,내수동,110-15,킹스매너,내수동 110-15 킹스매너,194.43,2004,200801,21~31,3.0,120000.0

In [3]:
# train 데이터 전체 정보 요약
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 804651 entries, 0 to 804650
Data columns (total 13 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   transaction_id          804651 non-null  int64
 1   apartment_id            804651 non-null  int64
 2   city                    804651 non-null  object
 3   dong                    804651 non-null  object
 4   jibun                   804651 non-null  object
 5   apt                     804651 non-null  object
 6   addr_kr                 804651 non-null  object
 7   exclusive_use_area      804651 non-null  float64
 8   year_of_completion      804651 non-null  int64
 9   transaction_year_month  804651 non-null  int64
 10  transaction_date        804650 non-null  object
 11  floor                   804650 non-null  float64
 12  transaction_real_price  804650 non-null  float64
dtypes: float64(3), int64(4), object(6)
memory usage: 79.8+ MB

In [4]:
# 각 컬럼별 결측값 개수 출력
train.isnull().sum()

transaction_id            0
apartment_id              0
city                      0
dong                      0
jibun                     0
apt                       0
addr_kr                   0
exclusive_use_area        0
year_of_completion        0
transaction_year_month    0
transaction_date          1
floor                     1
transaction_real_price    1
dtype: int64

In [5]:
# 수치형 컬럼의 통계를 요약하여 출력
train.describe()

,transaction_id,apartment_id,exclusive_use_area,year_of_completion,transaction_year_month,floor,transaction_real_price
count,804651.000000,804651.000000,804651.000000,804651.000000,804651.000000,804650.000000,804650.000000
mean,402325.000000,6390.409942,77.648589,1998.050828,201259.323806,9.062873,42140.731621
std,232282.880063,3551.974980,29.115558,8.946802,352.614545,6.301706,31468.413659
min,0.000000,0.000000,9.260000,1961.000000,20.000000,-4.000000,100.000000
25%,201162.500000,3594.000000,59.710000,1992.000000,201007.000000,4.000000,23500.000000
50%,402325.000000,6035.000000,82.390000,1999.000000,201308.000000,8.000000,34900.000000
75%,603487.500000,9508.000000,84.962000,2005.000000,201505.000000,13.000000,51000.000000
max,804650.000000,12658.000000,424.320000,2016.000000,201612.000000,69.000000,820000.000000

In [6]:
# 범주형 컬럼 통계 요약 출력
train.describe(include=['object'])

          city    dong   jibun     apt           addr_kr transaction_date
count   804651  804651  804651  804651            804651           804650
unique       2     412    7380    8465             10096                6
top      서울특별시     상계동  176-30      현대  용호동 944 오륙도에스케이뷰            11~20
freq    650921   25797    6374    8875              3097           270541

add_kr 주소

In [7]:
train['city'].value_counts()

city
서울특별시    650921
부산광역시    153730
Name: count, dtype: int64

In [8]:
train['city']=='부산광역시'

0         False
1         False
2         False
3         False
4         False
          ...
804646     True
804647     True
804648     True
804649     True
804650     True
Name: city, Length: 804651, dtype: bool

In [9]:
train[train['city']=='부산광역시']

,transaction_id,apartment_id,city,dong,jibun,apt,addr_kr,exclusive_use_area,year_of_completion,transaction_year_month,transaction_date,floor,transaction_real_price
650921,650921,3310,부산광역시,영주동,160,동아(160-0),영주동 160 동아(160-0),57.0900,1998,200801,1~10,4.0,7900.0
650922,650922,2939,부산광역시,영주동,587,도경오벨리스,영주동 587 도경오벨리스,84.9700,2005,200801,1~10,12.0,13000.0
650923,650923,1704,부산광역시,영주동,161,금호,영주동 161 금호,84.8600,1997,200801,11~20,7.0,12400.0
650924,650924,3310,부산광역시,영주동,160,동아(160-0),영주동 160 동아(160-0),84.7200,1998,200801,11~20,14.0,10600.0
650925,650925,1704,부산광역시,영주동,161,금호,영주동 161 금호,84.5900,1997,200801,21~31,5.0,10000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
804646,804646,2917,부산광역시,덕천동,373-1,덕천삼정그린코아,덕천동 373-1 덕천삼정그린코아,59.6165,2007,200904,21~30,13.0,11000.0
804647,804647,4438,부산광역시,덕천동,361,목화,덕천동 361 목화,62.8000,1979,200904,21~30,1.0,8100.0
804648,804648,3973,부산광역시,덕천동,132-65,롯데,덕천동 132-65 롯데,84.7504,2004,200904,21~30,11.0,13500.0
804649,804649,2919,부산광역시,덕천동,802,덕천주공1,덕천동 802 덕천주공1,38.6400,1991,200904,21~30,3.0,4190.0
804650,804650,2919,부산광역시,덕천동,802,덕천주공1,덕천동 802 덕천주공1,41.3000,1991,20,NaN,NaN,NaN

In [10]:
train.loc[train['city']=='부산광역시',:]

,transaction_id,apartment_id,city,dong,jibun,apt,addr_kr,exclusive_use_area,year_of_completion,transaction_year_month,transaction_date,floor,transaction_real_price
650921,650921,3310,부산광역시,영주동,160,동아(160-0),영주동 160 동아(160-0),57.0900,1998,200801,1~10,4.0,7900.0
650922,650922,2939,부산광역시,영주동,587,도경오벨리스,영주동 587 도경오벨리스,84.9700,2005,200801,1~10,12.0,13000.0
650923,650923,1704,부산광역시,영주동,161,금호,영주동 161 금호,84.8600,1997,200801,11~20,7.0,12400.0
650924,650924,3310,부산광역시,영주동,160,동아(160-0),영주동 160 동아(160-0),84.7200,1998,200801,11~20,14.0,10600.0
650925,650925,1704,부산광역시,영주동,161,금호,영주동 161 금호,84.5900,1997,200801,21~31,5.0,10000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
804646,804646,2917,부산광역시,덕천동,373-1,덕천삼정그린코아,덕천동 373-1 덕천삼정그린코아,59.6165,2007,200904,21~30,13.0,11000.0
804647,804647,4438,부산광역시,덕천동,361,목화,덕천동 361 목화,62.8000,1979,200904,21~30,1.0,8100.0
804648,804648,3973,부산광역시,덕천동,132-65,롯데,덕천동 132-65 롯데,84.7504,2004,200904,21~30,11.0,13500.0
804649,804649,2919,부산광역시,덕천동,802,덕천주공1,덕천동 802 덕천주공1,38.6400,1991,200904,21~30,3.0,4190.0
804650,804650,2919,부산광역시,덕천동,802,덕천주공1,덕천동 802 덕천주공1,41.3000,1991,20,NaN,NaN,NaN

In [13]:
train.loc[train['city']=='부산광역시',['year_of_completion','transaction_year_month']]

        year_of_completion  transaction_year_month
650921                1998                  200801
650922                2005                  200801
650923                1997                  200801
650924                1998                  200801
650925                1997                  200801
...                    ...                     ...
804646                2007                  200904
804647                1979                  200904
804648                2004                  200904
804649                1991                  200904
804650                1991                      20

[153730 rows x 2 columns]

In [16]:
train.iloc[:,[8,9]]

        year_of_completion  transaction_year_month
0                     2002                  200801
1                     1973                  200801
2                     2007                  200801
3                     2003                  200801
4                     2004                  200801
...                    ...                     ...
804646                2007                  200904
804647                1979                  200904
804648                2004                  200904
804649                1991                  200904
804650                1991                      20

[804651 rows x 2 columns]

In [17]:
train.iloc[9:20,[8,9]]

    year_of_completion  transaction_year_month
9                 2006                  200801
10                2004                  200801
11                2002                  200801
12                2003                  200801
13                1999                  200801
14                1999                  200801
15                1999                  200801
16                1999                  200801
17                1968                  200801
18                1999                  200801
19                1999                  200801

2단계 EDA

In [22]:
import pip
!pip install seaborn

Requirement already satisfied: seaborn in /usr/local/lib/python3.12/dist-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /usr/local/lib/python3.12/dist-packages (from seaborn) (2.0.2)
Requirement already satisfied: pandas>=1.2 in /usr/local/lib/python3.12/dist-packages (from seaborn) (2.2.2)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /usr/local/lib/python3.12/dist-packages (from seaborn) (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.2->seaborn) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)

In [29]:
# 파이썬 warning 무시
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)


# 시각화를 위한 라이브러리
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm

# 한글 폰트를 사용하기 위한 코드
fe = fm.FontEntry(fname = 'NotoSansKR-Regular.otf', name = 'NotoSansKR')
fm.fontManager.ttflist.insert(0, fe)
plt.rc('font',  family='NotoSansKR')

In [30]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

plt.style.use("fivethirtyeight")

In [31]:
train = pd.read_csv('train.csv')

In [32]:
train.head(2)

,transaction_id,apartment_id,city,dong,jibun,apt,addr_kr,exclusive_use_area,year_of_completion,transaction_year_month,transaction_date,floor,transaction_real_price
0,0,7622,서울특별시,신교동,6-13,신현(101동),신교동 6-13 신현(101동),84.82,2002,200801,21~31,2,37500
1,1,5399,서울특별시,필운동,142,사직파크맨션,필운동 142 사직파크맨션,99.17,1973,200801,1~10,6,20000

In [33]:
#transaction_year_month 연도와 월을 분리해 줍니다
train['year'] = train['transaction_year_month'].astype(str).str[:4].astype(int)
train['month'] = train['transaction_year_month'].astype(str).str[4:].astype(int)

In [35]:
train.head()

,transaction_id,apartment_id,city,dong,jibun,apt,addr_kr,exclusive_use_area,year_of_completion,transaction_year_month,transaction_date,floor,transaction_real_price,year,month
0,0,7622,서울특별시,신교동,6-13,신현(101동),신교동 6-13 신현(101동),84.82,2002,200801,21~31,2,37500,2008,1
1,1,5399,서울특별시,필운동,142,사직파크맨션,필운동 142 사직파크맨션,99.17,1973,200801,1~10,6,20000,2008,1
2,2,3578,서울특별시,필운동,174-1,두레엘리시안,필운동 174-1 두레엘리시안,84.74,2007,200801,1~10,6,38500,2008,1
3,3,10957,서울특별시,내수동,95,파크팰리스,내수동 95 파크팰리스,146.39,2003,200801,11~20,15,118000,2008,1
4,4,10639,서울특별시,내수동,110-15,킹스매너,내수동 110-15 킹스매너,194.43,2004,200801,21~31,3,120000,2008,1

transaction_date

In [36]:
train['transaction_date'].value_counts()

transaction_date
11~20    408385
1~10     391715
21~31    250588
21~30    134017
21~28     22199
21~29      9649
Name: count, dtype: int64

In [38]:
# transaction_date에서 21~31, 21~30, 21~28, 21~29에 해당하는 값을 21~31로 변환

# 막대기 대신 리스트를 써서 깔끔하게 줄이는 방법
targets = ['21~30', '21~28', '21~29']
train.loc[train['transaction_date'].isin(targets), 'transaction_date'] = '21~31'

In [40]:
train['transaction_date'].value_counts()

transaction_date
21~31    416453
11~20    408385
1~10     391715
Name: count, dtype: int64

plt.figure  가로크기 세로크기
plt.그래프 종류() or sns.그래프 종류()
사용하고 싶은 그래프 종류에 따라 맞춰서 종류를 사용해야하고, 패키지에 있는 그래프 종류를 사용하면됩니다

In [41]:
# pie chart

seoul_busan = train['city'].value_counts()
seoul_busan

city
서울특별시    742285
부산광역시    474268
Name: count, dtype: int64

In [42]:
# matplotilb plt.pie를 이용해 파이차트 그려보기

color = ['yellowgreen', 'gold']
iangs = ['서울특별시',  '부산광역시']

In [47]:
plt.figure(figsize=(8,6))
plt.pie(seoul_busan, labels=iangs, colors=color, autopct='% 2%%'
plt.title(' 서울과 부산의 아파트 거래 데이터 비\율     (size=20)

SyntaxError: unterminated string literal (detected at line 3) (3806824049.py, line 3)